language: go
go:
  - 1.12.x
sudo: required
dist: xenial
services:
- docker
env:
- RESYNC_PERIOD=30s
before_install:
- sudo snap install microk8s --classic --channel=1.11/stable
# This is a temporary fix. See: https://github.com/ubuntu/microk8s/issues/455
- sudo chmod 766 /var/snap/microk8s/current/args/kube-controller-manager
- echo "--cluster-signing-cert-file=\${SNAP_DATA}/certs/ca.crt" >> /var/snap/microk8s/current/args/kube-controller-manager
- echo "--cluster-signing-key-file=\${SNAP_DATA}/certs/ca.key" >> /var/snap/microk8s/current/args/kube-controller-manager
- sudo service snap.microk8s.daemon-controller-manager restart
- curl -Lo $GOPATH/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.11.7/bin/linux/amd64/kubectl
- curl -Lo $GOPATH/bin/dep https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-amd64
- curl -L https://raw.githubusercontent.com/alecthomas/gometalinter/master/scripts/install.sh
  | bash -s -- -b $GOPATH/bin
- chmod +x $GOPATH/bin/*
- echo $PATH && ls -la $GOPATH/bin
install: true
before_script:
- git clone --depth=1 https://github.com/kubernetes/kubernetes.git $GOPATH/src/k8s.io/kubernetes
script:
- "./ci/test.sh && ./ci/build.sh && ./ci/package.sh"

after_success:
- "./ci/build-release-files.sh"
deploy:
  provider: releases
  api_key:
    secure: pKwYDEsLMyFr1zwiKvxiS2qIn2dy+q/aCxzFHId0gIx/835yadoKarUtNOLJg6rNj536040MmLR9XSSfKMaZbRVPol6sER8pgglPOwKdmJ4T9asKnjKkkO4tkDJDmDWkTJJ/Gu8P0Hp0v7eyKvcyipvmTs9wXuPXdAR7S9oZANQhZ0yRkULgZc18LdsXuVVZW/J06JmIdtqdYLNq2WS/S8p7xwBBbLGKAjg2q6DsNgwetAY1Os+v+Wp4qJgmC2U+mmOrFJXQoSOtk1EkEHQNTdGRvATev4uG8Rl8f4rXa6W1Vt+n8p4KHbp7KkQXPODORzSJopAWqslFOXOdJMKhfyjsJtzoKQ7eO7dI3d1VEXrvniFjzeMjIxGDgSzKnK/dVUSs5i6ELpwVXAI/AvJz53Vo93C0BjWyzRppQcgidgWIR/8997hrQkOxichvKCScWTdO06W+m4xFuayRBN1sq5hVxCpZkrOCMJggrszqNQtg/M0eEoZW8NzLbbxzCYsDrwnf2xrPksbbb/c6Y1y6uT+tbyZWxiJPkN3fMKWWNyw/qkSdOXXybo1+70QY+GQiO2dxvbh6jRW2XizU9B3PGjd7MnnI7FuQtoNZotsPqgAiZw7QlFtaJ3zl95lBFLxqzaYHJcFY6bQiNB6pAjvldYHVQQqTwLU5w525qW9DTzY=
  file_glob: true
  file:
    - "release-files/*.tgz"
    - "release-files/sha256sums.txt"
    - "release-files/kubernetes-deployment.yaml"
  skip_cleanup: true
  on:
    tags: true
